### ISSUE TITLE
announcement.html is broken

### ISSUE THREAD

**Issue by Darktrader** [fallenPineapple/NPFchan#129]
Hello. When I added announcements and after that clicked on "show all" button below I redirected to _announcement.html_ page, but this page was blank. I saw only title "Announcement" in the upper part of the page.  Except of this, it didn't contain any other information.

**Comment by PupperWoff** [comment]
Thanks for notifying, I have updated the js script that handles the announcement list on the page.
The error was that it tried to read   "//announcements.js" and failed.
Please let me know it you still have problems.
