### ISSUE TITLE
Deleting something via the moderator interface inside a thread takes you back to the thread index

### ISSUE THREAD

**Issue by animepony** [fallenPineapple/NPFchan#15]
If you are moderating several items in a thread, this could become cumbersome.

**Comment by PupperWoff** [comment]
Created a BugFix for this issue,

Bugfix - Issue #15 - You are no longer taken to index if deleting post within a thread, but to the thread, only if you delete the whole thread are you taken to the index. If you delete reply from within index you are taken to the thread.

**Comment by fallenPineapple** [comment]
#70

**Comment by animepony** [comment]
Issue resolved. Wonderful!
